name: Jason Cordes
markdown: kramdown
theme: minima
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
title: Cyborg Hobbitâ€™s blog
description: Welcome to my blog
author: Cyborg Hobbit
